### ISSUE TITLE
RuntimeError: Given groups=1, weight of size [128, 128, 3, 3], expected input[32, 256, 20, 20] to have 128 channels, but got 256 channels instead

### ISSUE THREAD

**Issue by sunmingqi-1** [SwjtuMa/FER-YOLO-Mamba#10]
(YOLO_Mamba) [pc_stu2@localhost FER-YOLO-Mamba-main]$ python train.py
No module named 'selective_scan_cuda_core'
initialize network with normal type
Load weights model_data/yolox_s.pth.

Successful Load Key: ['backbone.backbone.stem.conv.conv.weight', 'backbone.backbone.stem.conv.bn.weight', 'backbone.backbone.stem.conv.bn.bias', 'backbone.backbone.stem.conv.bn.running_mean', 'backbone.backbone.stem.conv.bn.running_var', 'backbone.backbone.stem.conv.bn.num_batches_tracked', 'backbone.backbone.dark2.0.conv.weight', 'backbone.backbone.dark2.0.bn.weight', 'backbone.backbone.dark2.0.bn.bias', 'backbone.backbone.dark2.0.bn.running_mean', 'backbone.backbone.dark2.0.bn.running_var', 'backbone.backbone.dark ……
Successful Load Key Num: 334

Fail To Load Key: ['backbone.C3_p4.conv1.conv.weight', 'backbone.C3_p4.conv1.bn.weight', 'backbone.C3_p4.conv1.bn.bias', 'backbone.C3_p4.conv1.bn.running_mean', 'backbone.C3_p4.conv1.bn.running_var', 'backbone.C3_p4.conv1.bn.num_batches_tracked', 'backbone.C3_p4.conv2.conv.weight', 'backbone.C3_p4.conv2.bn.weight', 'backbone.C3_p4.conv2.bn.bias', 'backbone.C3_p4.conv2.bn.running_mean', 'backbone.C3_p4.conv2.bn.running_var', 'backbone.C3_p4.conv2.bn.num_batches_tracked', 'backbone.C3_p4.conv3.conv.weight', 'backbo ……
Fail To Load Key num: 128
Expected u.is_cuda() to be true, but got false.  (Could this error message be improved?  If so, please report an enhancement request to PyTorch.)
Error occurs, No graph saved
Configurations:
----------------------------------------------------------------------
|                     keys |                                   values|
----------------------------------------------------------------------
|             classes_path |              model_data/sfew_classes.txt|
|               model_path |                   model_data/yolox_s.pth|
|              input_shape |                               [320, 320]|
|               Init_Epoch |                                        0|
|             Freeze_Epoch |                                      100|
|           UnFreeze_Epoch |                                      300|
|        Freeze_batch_size |                                       32|
|      Unfreeze_batch_size |                                       16|
|             Freeze_Train |                                     True|
|                  Init_lr |                                     0.01|
|                   Min_lr |                                   0.0001|
|           optimizer_type |                                      sgd|
|                 momentum |                                    0.937|
|            lr_decay_type |                                      cos|
|              save_period |                                       10|
|                 save_dir |                                     logs|
|              num_workers |                                        0|
|                num_train |                                     1125|
|                  num_val |                                      126|
----------------------------------------------------------------------
Start Train
Epoch 1/300:   0%|                                                                                                                                                                                  | 0/35 [00:00<?, ?it/s<class 'dict'>]Traceback (most recent call last):
  File "/home/pc_stu2/Projects/FER-YOLO-Mamba-main/train.py", line 236, in <module>
    fit_one_epoch(model_train, model, ema, yolo_loss, loss_history, eval_callback, optimizer, epoch, epoch_step, epoch_step_val, gen, gen_val, UnFreeze_Epoch, Cuda, fp16, scaler, save_period, save_dir, local_rank)
  File "/home/pc_stu2/Projects/FER-YOLO-Mamba-main/utils/utils_fit.py", line 34, in fit_one_epoch
    outputs         = model_train(images)
                      ^^^^^^^^^^^^^^^^^^^
  File "/home/pc_stu2/anaconda3/envs/YOLO_Mamba/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pc_stu2/Projects/FER-YOLO-Mamba-main/nets/yolo.py", line 996, in forward
    outputs     = self.head.forward(fpn_outs)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pc_stu2/Projects/FER-YOLO-Mamba-main/nets/yolo.py", line 892, in forward
    cls_feat    = self.cls_convs[k](x)
                  ^^^^^^^^^^^^^^^^^^^^
  File "/home/pc_stu2/anaconda3/envs/YOLO_Mamba/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pc_stu2/anaconda3/envs/YOLO_Mamba/lib/python3.11/site-packages/torch/nn/modules/container.py", line 217, in forward
    input = module(input)
            ^^^^^^^^^^^^^
  File "/home/pc_stu2/anaconda3/envs/YOLO_Mamba/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pc_stu2/Projects/FER-YOLO-Mamba-main/nets/darknet.py", line 46, in forward
    return self.act(self.bn(self.conv(x)))
                            ^^^^^^^^^^^^
  File "/home/pc_stu2/anaconda3/envs/YOLO_Mamba/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pc_stu2/anaconda3/envs/YOLO_Mamba/lib/python3.11/site-packages/torch/nn/modules/conv.py", line 463, in forward
    return self._conv_forward(input, self.weight, self.bias)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pc_stu2/anaconda3/envs/YOLO_Mamba/lib/python3.11/site-packages/torch/nn/modules/conv.py", line 459, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: Given groups=1, weight of size [128, 128, 3, 3], expected input[32, 256, 20, 20] to have 128 channels, but got 256 channels instead
Epoch 1/300:   0%|

**Comment by hafsa390** [comment]
@sunmingqi-1 , did you solve it?

**Comment by sunmingqi-1** [comment]
@hafsa390 是的，我已经解决了这个问题。你只需要修改一下YOLOHead  的网络结构。在其 forward中的for 循环中，添加 x=self.stems[k](x) 即可。
