### ISSUE TITLE
Can't run predict.py

### ISSUE THREAD

**Issue by charkoteow** [SwjtuMa/FER-YOLO-Mamba#2]
Would like to test out the model for facial expression.

Getting the following error when trying to run predict.py

```
Traceback (most recent call last):
  File "FER-YOLO-Mamba-main/predict.py", line 7, in <module>
    from yolo import YOLO
ModuleNotFoundError: No module named 'yolo'
```

Do I need Ultralytics first? What else do I need to get it running besides the requirements in the readme?

**Comment by SwjtuMa** [comment]
> Would like to test out the model for facial expression.
> 
> Getting the following error when trying to run predict.py
> 
> ```
> Traceback (most recent call last):
>   File "FER-YOLO-Mamba-main/predict.py", line 7, in <module>
>     from yolo import YOLO
> ModuleNotFoundError: No module named 'yolo'
> ```
> 
> Do I need Ultralytics first? What else do I need to get it running besides the requirements in the readme?

I've uploaded yolo.py, you don't need to install other libraries, you can test it directly.

**Comment by charkoteow** [comment]
Thank you!

I am now facing this error if you don't mind sharing how to solve it.

```
No module named 'selective_scan_cuda_core'
Traceback (most recent call last):
  File "FER-YOLO-Mamba-main/predict.py", line 10, in <module>
    yolo = YOLO()
  File "FER-YOLO-Mamba-main/yolo.py", line 39, in __init__
    self.generate()
  File "FER-YOLO-Mamba-main/yolo.py", line 44, in generate
    self.net.load_state_dict(torch.load(self.model_path, map_location=device))
  File "FER-YOLO-Mamba-main/lib/python3.10/site-packages/torch/serialization.py", line 791, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "FER-YOLO-Mamba-main/lib/python3.10/site-packages/torch/serialization.py", line 271, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "FER-YOLO-Mamba-main/lib/python3.10/site-packages/torch/serialization.py", line 252, in __init__
    super().__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: 'logs/best_epoch_weights.pth'


```

The module selective_cuda_core should come with the installation of mamba_ssm yes? I've installed it with no errors, not sure what this is about.

Also the last line means the weight is not there yet right? I haven't run any training, just trying to run sample predictions. Do I need to run training first? If so, I will need the images from VOCdevkit/VOC2007 yes? Can you guide me where to get the dataset?

Sorry for the troubles.
